import { useState } from 'react'
import {
  profile as defaultProfile,
  projects as defaultProjects,
  experience as defaultExperience,
  skills as defaultSkills,
  testimonials as defaultTestimonials,
  certifications as defaultCerts,
  education as defaultEducation,
} from '../data/content'

const STORAGE_KEY = 'masskay_admin_content'

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? JSON.parse(raw) : null
  } catch {
    return null
  }
}

function persist(data) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data))
}

const DEFAULTS = {
  profile: defaultProfile,
  projects: defaultProjects,
  experience: defaultExperience,
  skills: defaultSkills,
  testimonials: defaultTestimonials,
  certifications: defaultCerts,
  education: defaultEducation,
}

export function useAdminData() {
  const [data, setData] = useState(() => loadFromStorage() ?? DEFAULTS)
  const [saved, setSaved] = useState(true)

  function update(section, value) {
    setData(prev => {
      const next = { ...prev, [section]: value }
      persist(next)
      return next
    })
    setSaved(true)
  }

  function reset() {
    setData(DEFAULTS)
    localStorage.removeItem(STORAGE_KEY)
  }

  return { data, update, reset, saved }
}

export function generateContentJs(data) {
  const s = v => JSON.stringify(v, null, 2)
  return `// Auto-generated by Masskay Admin — ${new Date().toLocaleDateString()}
// Copy this file to src/data/content.js and redeploy.

export const profile = ${s(data.profile)}

export const skills = ${s(data.skills)}

export const projects = ${s(data.projects)}

export const experience = ${s(data.experience)}

export const education = ${s(data.education)}

export const certifications = ${s(data.certifications)}

export const testimonials = ${s(data.testimonials)}

export const tickerItems = [
  "SQL", "Python", "Power BI", "Tableau", "Excel",
  "dbt", "BigQuery", "Pandas", "Snowflake", "Looker", "R", "Airflow", "Azure",
]
`
}
